services:
  # React Development Server
  react-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3050:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://flask-dev:5000
      - GENERATE_SOURCEMAP=false
    stdin_open: true
    tty: true
    depends_on:
      - flask-dev

  # Flask Development Server
  flask-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - MAILERSEND_API_KEY=${MAILERSEND_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mailhog

  # MailHog - Email testing tool
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"  # SMTP server (changed from 1025 to avoid conflict)
      - "8026:8025"  # Web UI (changed from 8025 to avoid conflict)
    restart: unless-stopped

volumes:
  node_modules:
